[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "adetsim",
]

[tool.setuptools.package-data]
"adetsim" = ["styles/*"]

[project]
version = "0"
name = "adetsim"
dependencies = [
    "asdf",
    "asdf_astropy",
    "astropy",
    "matplotlib",
    "numpy",
    "pymsis",
    "requests",
    "scipy",
    "sunpy[all]",
    "sunkit_spex @ git+https://github.com/sunpy/sunkit-spex.git",
    "jupyter",
    "ipynb",
    "pyqt6"
]